// Market-ticker abbr -> team. Names, helmet slugs and colours match the
// deployed board (colours are pre-brightened to read on black).

window.Board = window.Board || {};

Board.TEAMS = {
    ARI: { name: 'Arizona',       slug: 'ARI', color: '#97233F' },
    ATL: { name: 'Atlanta',       slug: 'ATL', color: '#A71930' },
    BAL: { name: 'Baltimore',     slug: 'BAL', color: '#5B4BC4' },
    BUF: { name: 'Buffalo',       slug: 'BUF', color: '#3A6BE0' },
    CAR: { name: 'Carolina',      slug: 'CAR', color: '#0085CA' },
    CHI: { name: 'Chicago',       slug: 'CHI', color: '#C83803' },
    CIN: { name: 'Cincinnati',    slug: 'CIN', color: '#FB4F14' },
    CLE: { name: 'Cleveland',     slug: 'CLE', color: '#FF3C00' },
    DAL: { name: 'Dallas',        slug: 'DAL', color: '#3C82FF' },
    DEN: { name: 'Denver',        slug: 'DEN', color: '#FB4F14' },
    DET: { name: 'Detroit',       slug: 'DET', color: '#0076B6' },
    GB:  { name: 'Green Bay',     slug: 'GB',  color: '#FFB612' },
    HOU: { name: 'Houston',       slug: 'HOU', color: '#A71930' },
    IND: { name: 'Indianapolis',  slug: 'IND', color: '#3A6BE0' },
    JAC: { name: 'Jacksonville',  slug: 'JAX', color: '#00A8B0' },
    JAX: { name: 'Jacksonville',  slug: 'JAX', color: '#00A8B0' },
    KC:  { name: 'Kansas City',   slug: 'KC',  color: '#E31837' },
    LA:  { name: 'LA Rams',       slug: 'LA',  color: '#FFA300' },
    LAR: { name: 'LA Rams',       slug: 'LA',  color: '#FFA300' },
    LAC: { name: 'LA Chargers',   slug: 'LAC', color: '#4FA8E0' },
    LV:  { name: 'Las Vegas',     slug: 'LV',  color: '#A5ACAF' },
    MIA: { name: 'Miami',         slug: 'MIA', color: '#00C2D1' },
    MIN: { name: 'Minnesota',     slug: 'MIN', color: '#8A5EC8' },
    NE:  { name: 'New England',   slug: 'NE',  color: '#C60C30' },
    NO:  { name: 'New Orleans',   slug: 'NO',  color: '#D3BC8D' },
    NYG: { name: 'New York',      slug: 'NYG', color: '#C81D39' },
    NYJ: { name: 'New York',      slug: 'NYJ', color: '#00B77A' },
    PHI: { name: 'Philadelphia',  slug: 'PHI', color: '#00A8A8' },
    PIT: { name: 'Pittsburgh',    slug: 'PIT', color: '#FFB612' },
    SEA: { name: 'Seattle',       slug: 'SEA', color: '#69BE28' },
    SF:  { name: 'San Francisco', slug: 'SF',  color: '#D9312B' },
    TB:  { name: 'Tampa Bay',     slug: 'TB',  color: '#FF4747' },
    TEN: { name: 'Tennessee',     slug: 'TEN', color: '#4B92DB' },
    WAS: { name: 'Washington',    slug: 'WAS', color: '#FFB612' },
};
